theme: jekyll-theme-cayman
title: Welcome to JackBai's Blog on Github!
description: This Blog is for testing and recording the things I have learnt and ideas I have thought about. 
Thanks for reading and feel free to comment so long as I know how to deploy a comment function.
